# Generated by Django 3.1.3 on 2020-11-12 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_blog_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 12, 9, 41, 24, 842134, tzinfo=utc)),
        ),
    ]
